# ch14-Testing_Debugging_and_Exceptions()

## 目錄

- [ch14-Testing_Debugging_and_Exceptions()](#ch14-testing_debugging_and_exceptions)
	- [目錄](#目錄)
- [內容](#內容)
	- [14.1 測試送至stdout的輸出](#141-測試送至stdout的輸出)
	- [14.2 在單元測試中修補物件](#142-在單元測試中修補物件)
	- [14.3 在單元測試中測試例外條件](#143-在單元測試中測試例外條件)
	- [14.4 將測試輸出記錄到一個檔案](#144-將測試輸出記錄到一個檔案)
	- [14.5 跳過測試或預期測試失敗](#145-跳過測試或預期測試失敗)
	- [14.6 處理多個例外](#146-處理多個例外)
	- [14.7 捕捉所有的例外](#147-捕捉所有的例外)
	- [14.8 建立自訂的例外](#148-建立自訂的例外)
	- [14.9 為了處理一個例外而提出另一個例外](#149-為了處理一個例外而提出另一個例外)
	- [14.10 重新提出上一個例外](#1410-重新提出上一個例外)
	- [14.11 發出警告訊息](#1411-發出警告訊息)
	- [14.12 程式當掉時的基本除錯](#1412-程式當掉時的基本除錯)
	- [14.13 為你的程式進行效能評測與計時](#1413-為你的程式進行效能評測與計時)
	- [14.14 讓你的程式跑得更快](#1414-讓你的程式跑得更快)

# 內容

## 14.1 測試送至stdout的輸出

問題：

```
```

解法：

```
```

討論：

```
```

範例：

```Python
```

## 14.2 在單元測試中修補物件

問題：

```
```

解法：

```
```

討論：

```
```

範例：

```Python
```

## 14.3 在單元測試中測試例外條件

問題：

```
```

解法：

```
```

討論：

```
```

範例：

```Python
```

## 14.4 將測試輸出記錄到一個檔案

問題：

```
```

解法：

```
```

討論：

```
```

範例：

```Python
```

## 14.5 跳過測試或預期測試失敗

問題：

```
```

解法：

```
```

討論：

```
```

範例：

```Python
```

## 14.6 處理多個例外

問題：

```
```

解法：

```
```

討論：

```
```

範例：

```Python
```

## 14.7 捕捉所有的例外

問題：

```
```

解法：

```
```

討論：

```
```

範例：

```Python
```

## 14.8 建立自訂的例外

問題：

```
```

解法：

```
```

討論：

```
```

範例：

```Python
```

## 14.9 為了處理一個例外而提出另一個例外

問題：

```
```

解法：

```
```

討論：

```
```

範例：

```Python
```

## 14.10 重新提出上一個例外

問題：

```
```

解法：

```
```

討論：

```
```

範例：

```Python
```

## 14.11 發出警告訊息

問題：

```
```

解法：

```
```

討論：

```
```

範例：

```Python
```

## 14.12 程式當掉時的基本除錯

問題：

```
```

解法：

```
```

討論：

```
```

範例：

```Python
```

## 14.13 為你的程式進行效能評測與計時

問題：

```
```

解法：

```
```

討論：

```
```

範例：

```Python
```

## 14.14 讓你的程式跑得更快

問題：

```
```

解法：

```
```

討論：

```
```

範例：

```Python
```
